Hi,
I've been trying to use the osemosys cloud server because it seems great for reducing our solve time. However we are having a few issues with using it and I was wondering if you could please help us out. 
Please note that at our office we can't install coin-cbc on our computers (an issue with 'urtcbased.dll' missing which I don't know how to solve) to create the output_#####.txt file, so I don't know for sure what is causing this issue.

The issue:
During the run 30942 (i assume you can look at the log file) i got an error which i have inspected in the postprocess.py code and i expect the code wasn't built to handle this output:

    ### CoinLpIO::is_invalid_name(): Name EBa1_RateOfFuelProduction1('19_THA',WW0004,'17_electricity_imports',POW_17_electricity_imports,1,2017) is too long

    588  Obj 2.0539027e+08 Primal inf 1119968.4 (3781) Dual inf 3.1589468e+14 (5582)

These issues occur on lines 236 to 234 of postprocess_results.py. I am happy to help make the code handle this properly but i need to know whether it is actually those lines causing the error. 

Note that i think both of these lines could be causing the error.
 - I can change the model file to reduce those variable name lengths and keep the first line from causing issues. 
 - But I assume the 2nd line should be able to be in the output file (I think it's because Dual inf and Primal inf are occuring on the same line, where normally the code can handle jsut one of them occuring on the same line).
